// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "github.com/sagoo-cloud/sagooiot/internal/logic/alarm"
	_ "github.com/sagoo-cloud/sagooiot/internal/logic/common"
	_ "github.com/sagoo-cloud/sagooiot/internal/logic/context"
	_ "github.com/sagoo-cloud/sagooiot/internal/logic/datahub"
	_ "github.com/sagoo-cloud/sagooiot/internal/logic/envirotronics"
	_ "github.com/sagoo-cloud/sagooiot/internal/logic/middleware"
	_ "github.com/sagoo-cloud/sagooiot/internal/logic/network"
	_ "github.com/sagoo-cloud/sagooiot/internal/logic/notice"
	_ "github.com/sagoo-cloud/sagooiot/internal/logic/product"
	_ "github.com/sagoo-cloud/sagooiot/internal/logic/system"
	_ "github.com/sagoo-cloud/sagooiot/internal/logic/tdengine"
)
