// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// BaseDbLink is the golang structure of table base_db_link for DAO operations like Where/Data.
type BaseDbLink struct {
	g.Meta      `orm:"table:base_db_link, do:true"`
	Id          interface{} //
	Name        interface{} // 名称
	Types       interface{} // 驱动类型 mysql或oracle
	Host        interface{} // 主机地址
	Port        interface{} // 端口号
	UserName    interface{} // 用户名称
	Password    interface{} // 密码
	Description interface{} // 描述
	Status      interface{} // 状态 0 停用 1启用
	IsDeleted   interface{} // 是否删除 0未删除 1已删除
	CreatedBy   interface{} // 创建人
	CreatedAt   *gtime.Time // 创建时间
	UpdatedBy   interface{} // 修改人
	UpdatedAt   *gtime.Time // 更新时间
	DeletedBy   interface{} // 删除人
	DeletedAt   *gtime.Time // 删除时间
}
