// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// DataNode is the golang structure of table data_node for DAO operations like Where/Data.
type DataNode struct {
	g.Meta    `orm:"table:data_node, do:true"`
	NodeId    interface{} //
	SourceId  interface{} // 数据源ID
	Name      interface{} // 数据节点名称
	Key       interface{} // 数据节点标识
	DataType  interface{} // 数据类型
	Value     interface{} // 取值项
	IsPk      interface{} // 是否主键：0=否，1=是
	Rule      interface{} // 规则配置json
	CreateBy  interface{} // 创建者
	UpdateBy  interface{} // 更新者
	DeletedBy interface{} // 删除者
	CreatedAt *gtime.Time // 创建时间
	UpdatedAt *gtime.Time // 更新时间
	DeletedAt *gtime.Time // 删除时间
}
