// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// DataTemplateNode is the golang structure of table data_template_node for DAO operations like Where/Data.
type DataTemplateNode struct {
	g.Meta    `orm:"table:data_template_node, do:true"`
	Id        interface{} // ID
	Tid       interface{} // 模型ID
	From      interface{} // 字段生成方式:1=自动生成,2=数据源
	SourceId  interface{} // 数据源ID
	NodeId    interface{} // 数据源ID
	Name      interface{} // 节点名称
	Key       interface{} // 节点标识
	DataType  interface{} // 数据类型
	Default   interface{} // 默认值
	Method    interface{} // 数值类型，取值方式
	IsPk      interface{} // 是否主键：0=否，1=是
	Desc      interface{} // 描述
	CreateBy  interface{} // 创建者
	UpdateBy  interface{} // 更新者
	DeletedBy interface{} // 删除者
	CreatedAt *gtime.Time // 创建时间
	UpdatedAt *gtime.Time // 更新时间
	DeletedAt *gtime.Time // 删除时间
}
