// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// DataSource is the golang structure of table data_source for DAO operations like Where/Data.
type DataSource struct {
	g.Meta    `orm:"table:data_source, do:true"`
	SourceId  interface{} //
	Name      interface{} // 数据源名称
	Key       interface{} // 数据源标识
	Desc      interface{} // 描述
	From      interface{} // 数据来源：1=api导入，2=数据库，3=文件，4=设备
	Config    interface{} // 数据源配置json：api配置、数据库配置、文件配置
	Rule      interface{} // 规则配置json
	LockKey   interface{} // 锁定key标识：0=未锁定，1=锁定，不允许修改
	Status    interface{} // 状态：0=未发布，1=已发布
	DataTable interface{} // 数据表名称
	CreateBy  interface{} // 创建者
	UpdateBy  interface{} // 更新者
	DeletedBy interface{} // 删除者
	CreatedAt *gtime.Time // 创建时间
	UpdatedAt *gtime.Time // 更新时间
	DeletedAt *gtime.Time // 删除时间
}
