// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// DataTemplateBusi is the golang structure of table data_template_busi for DAO operations like Where/Data.
type DataTemplateBusi struct {
	g.Meta         `orm:"table:data_template_busi, do:true"`
	Id             interface{} //
	DataTemplateId interface{} // 数据建模ID
	BusiTypes      interface{} // 业务单元
	IsDeleted      interface{} // 0未删除 1已删除
	CreatedBy      interface{} // 创建人
	CreatedAt      *gtime.Time // 创建时间
	DeletedBy      interface{} // 删除人
	DeletedAt      *gtime.Time // 删除时间
}
