// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// DataTemplate is the golang structure of table data_template for DAO operations like Where/Data.
type DataTemplate struct {
	g.Meta         `orm:"table:data_template, do:true"`
	Id             interface{} // ID
	Name           interface{} // 名称
	Key            interface{} // 标识
	Desc           interface{} // 描述
	Status         interface{} // 状态：0=未发布，1=已发布
	CronExpression interface{} // cron执行表达式
	SortNodeKey    interface{} // 排序节点标识
	SortDesc       interface{} // 排序方式：1=倒序，2=正序
	DataTable      interface{} // 数据表名称
	LockKey        interface{} // 锁定key标识：0=未锁定，1=锁定，不允许修改
	MainSourceId   interface{} // 主数据源
	SourceNodeKey  interface{} // 数据源关联节点
	CreateBy       interface{} // 创建者
	UpdateBy       interface{} // 更新者
	DeletedBy      interface{} // 删除者
	CreatedAt      *gtime.Time // 创建时间
	UpdatedAt      *gtime.Time // 更新时间
	DeletedAt      *gtime.Time // 删除时间
}
