// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// DevDevice is the golang structure of table dev_device for DAO operations like Where/Data.
type DevDevice struct {
	g.Meta         `orm:"table:dev_device, do:true"`
	Id             interface{} //
	Key            interface{} // 设备标识
	Name           interface{} // 设备名称
	ProductId      interface{} // 所属产品
	Desc           interface{} // 描述
	MetadataTable  interface{} // 是否生成物模型子表：0=否，1=是
	Status         interface{} // 状态：0=未启用,1=离线,2=在线
	RegistryTime   *gtime.Time // 激活时间
	LastOnlineTime *gtime.Time // 最后上线时间
	Certificate    interface{} // 设备证书
	SecureKey      interface{} // 设备密钥
	Version        interface{} // 固件版本号
	TunnelId       interface{} // tunnelId
	CreateBy       interface{} // 创建者
	UpdateBy       interface{} // 更新者
	DeletedBy      interface{} // 删除者
	CreatedAt      *gtime.Time // 创建时间
	UpdatedAt      *gtime.Time // 更新时间
	DeletedAt      *gtime.Time // 删除时间
}
