// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysPlugins is the golang structure of table sys_plugins for DAO operations like Where/Data.
type SysPlugins struct {
	g.Meta    `orm:"table:sys_plugins, do:true"`
	Id        interface{} // ID
	Name      interface{} // 名称
	Title     interface{} // 标题
	Intro     interface{} // 介绍
	Version   interface{} // 版本
	Status    interface{} // 状态
	Types     interface{} // 插件类型
	Author    interface{} //
	StartTime *gtime.Time //
}
