// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// DataTemplateNodeDao is the data access object for table data_template_node.
type DataTemplateNodeDao struct {
	table   string                  // table is the underlying table name of the DAO.
	group   string                  // group is the database configuration group name of current DAO.
	columns DataTemplateNodeColumns // columns contains all the column names of Table for convenient usage.
}

// DataTemplateNodeColumns defines and stores column names for table data_template_node.
type DataTemplateNodeColumns struct {
	Id        string // ID
	Tid       string // 模型ID
	From      string // 字段生成方式:1=自动生成,2=数据源
	SourceId  string // 数据源ID
	NodeId    string // 数据源ID
	Name      string // 节点名称
	Key       string // 节点标识
	DataType  string // 数据类型
	Default   string // 默认值
	Method    string // 数值类型，取值方式
	IsPk      string // 是否主键：0=否，1=是
	Desc      string // 描述
	CreateBy  string // 创建者
	UpdateBy  string // 更新者
	DeletedBy string // 删除者
	CreatedAt string // 创建时间
	UpdatedAt string // 更新时间
	DeletedAt string // 删除时间
}

//  dataTemplateNodeColumns holds the columns for table data_template_node.
var dataTemplateNodeColumns = DataTemplateNodeColumns{
	Id:        "id",
	Tid:       "tid",
	From:      "from",
	SourceId:  "source_id",
	NodeId:    "node_id",
	Name:      "name",
	Key:       "key",
	DataType:  "data_type",
	Default:   "default",
	Method:    "method",
	IsPk:      "is_pk",
	Desc:      "desc",
	CreateBy:  "create_by",
	UpdateBy:  "update_by",
	DeletedBy: "deleted_by",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	DeletedAt: "deleted_at",
}

// NewDataTemplateNodeDao creates and returns a new DAO object for table data access.
func NewDataTemplateNodeDao() *DataTemplateNodeDao {
	return &DataTemplateNodeDao{
		group:   "default",
		table:   "data_template_node",
		columns: dataTemplateNodeColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *DataTemplateNodeDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *DataTemplateNodeDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *DataTemplateNodeDao) Columns() DataTemplateNodeColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *DataTemplateNodeDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *DataTemplateNodeDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *DataTemplateNodeDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
