// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"github.com/sagoo-cloud/sagooiot/internal/model"
)

type (
	IEnvWeather interface {
		CityWeatherList(ctx context.Context) (cityWeatherListOut []*model.CityWeatherListOut, err error)
		GetCityWeatherById(ctx context.Context, id int) (cityWeatherListOut *model.CityWeatherListOut, err error)
		GetCityTemperatureById(ctx context.Context, id int, types int) (cityWeatherEchartOut []*model.CityWeatherEchartOut, avgCityWeatherEchartOut []*model.CityWeatherEchartOut, foreCastCityWeatherEchartOut []*model.CityWeatherEchartOut, foreCastAvgCityWeatherEchartOut []*model.CityWeatherEchartOut, err error)
		GetCityWindpowerById(ctx context.Context, id int, types int) (cityWeatherEchartOut []*model.CityWeatherEchartOut, avgCityWeatherEchartOut []*model.CityWeatherEchartOut, foreCastCityWeatherEchartOut []*model.CityWeatherEchartOut, foreCastAvgCityWeatherEchartOut []*model.CityWeatherEchartOut, err error)
	}
)

var (
	localEnvWeather IEnvWeather
)

func EnvWeather() IEnvWeather {
	if localEnvWeather == nil {
		panic("implement not found for interface IEnvWeather, forgot register?")
	}
	return localEnvWeather
}

func RegisterEnvWeather(i IEnvWeather) {
	localEnvWeather = i
}
