// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"github.com/sagoo-cloud/sagooiot/internal/model"
)

type (
	INetworkServer interface {
		GetServerList(ctx context.Context, in *model.GetNetworkServerListInput) (total int, out []*model.NetworkServerOut, err error)
		GetServerRunList(ctx context.Context) (list []*model.NetworkServerRes, err error)
		GetServerById(ctx context.Context, id int) (out *model.NetworkServerOut, err error)
		AddServer(ctx context.Context, in model.NetworkServerAddInput) (err error)
		EditServer(ctx context.Context, in model.NetworkServerEditInput) (err error)
		DeleteServer(ctx context.Context, ids []int) (err error)
		SetServerStatus(ctx context.Context, id, status int) (err error)
	}
	INetworkTunnel interface {
		GetTunnelList(ctx context.Context, in *model.GetNetworkTunnelListInput) (total int, out []*model.NetworkTunnelOut, err error)
		GetTunnelRunList(ctx context.Context) (out []*model.NetworkTunnelOut, err error)
		GetTunnelById(ctx context.Context, id int) (out *model.NetworkTunnelOut, err error)
		AddTunnel(ctx context.Context, in model.NetworkTunnelAddInput) (id int, err error)
		EditTunnel(ctx context.Context, in model.NetworkTunnelEditInput) (err error)
		DeleteTunnel(ctx context.Context, ids []int) (err error)
		SetTunnelStatus(ctx context.Context, id, status int) (err error)
	}
)

var (
	localNetworkServer INetworkServer
	localNetworkTunnel INetworkTunnel
)

func NetworkServer() INetworkServer {
	if localNetworkServer == nil {
		panic("implement not found for interface INetworkServer, forgot register?")
	}
	return localNetworkServer
}

func RegisterNetworkServer(i INetworkServer) {
	localNetworkServer = i
}

func NetworkTunnel() INetworkTunnel {
	if localNetworkTunnel == nil {
		panic("implement not found for interface INetworkTunnel, forgot register?")
	}
	return localNetworkTunnel
}

func RegisterNetworkTunnel(i INetworkTunnel) {
	localNetworkTunnel = i
}
