// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sagooiot/internal/dao/internal"
)

// internalAlarmLogDao is internal type for wrapping internal DAO implements.
type internalAlarmLogDao = *internal.AlarmLogDao

// alarmLogDao is the data access object for table alarm_log.
// You can define custom methods on it to extend its functionality as you wish.
type alarmLogDao struct {
	internalAlarmLogDao
}

var (
	// AlarmLog is globally public accessible object for table alarm_log operations.
	AlarmLog = alarmLogDao{
		internal.NewAlarmLogDao(),
	}
)

// Fill with you ideas below.
