// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sagooiot/internal/dao/internal"
)

// internalAlarmRuleDao is internal type for wrapping internal DAO implements.
type internalAlarmRuleDao = *internal.AlarmRuleDao

// alarmRuleDao is the data access object for table alarm_rule.
// You can define custom methods on it to extend its functionality as you wish.
type alarmRuleDao struct {
	internalAlarmRuleDao
}

var (
	// AlarmRule is globally public accessible object for table alarm_rule operations.
	AlarmRule = alarmRuleDao{
		internal.NewAlarmRuleDao(),
	}
)

// Fill with you ideas below.
