// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sagooiot/internal/dao/internal"
)

// internalAlarmLevelDao is internal type for wrapping internal DAO implements.
type internalAlarmLevelDao = *internal.AlarmLevelDao

// alarmLevelDao is the data access object for table alarm_level.
// You can define custom methods on it to extend its functionality as you wish.
type alarmLevelDao struct {
	internalAlarmLevelDao
}

var (
	// AlarmLevel is globally public accessible object for table alarm_level operations.
	AlarmLevel = alarmLevelDao{
		internal.NewAlarmLevelDao(),
	}
)

// Fill with you ideas below.
