// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/sagoo-cloud/sagooiot/internal/dao/internal"
)

// internalCityDataDao is internal type for wrapping internal DAO implements.
type internalCityDataDao = *internal.CityDataDao

// cityDataDao is the data access object for table city_data.
// You can define custom methods on it to extend its functionality as you wish.
type cityDataDao struct {
	internalCityDataDao
}

var (
	// CityData is globally public accessible object for table city_data operations.
	CityData = cityDataDao{
		internal.NewCityDataDao(),
	}
)

// Fill with you ideas below.
