// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/sagoo-cloud/sagooiot/internal/dao/internal"
)

// internalDataSourceDao is internal type for wrapping internal DAO implements.
type internalDataSourceDao = *internal.DataSourceDao

// dataSourceDao is the data access object for table data_source.
// You can define custom methods on it to extend its functionality as you wish.
type dataSourceDao struct {
	internalDataSourceDao
}

var (
	// DataSource is globally public accessible object for table data_source operations.
	DataSource = dataSourceDao{
		internal.NewDataSourceDao(),
	}
)

// Fill with you ideas below.
