// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/sagoo-cloud/sagooiot/internal/dao/internal"
)

// internalDataTemplateNodeDao is internal type for wrapping internal DAO implements.
type internalDataTemplateNodeDao = *internal.DataTemplateNodeDao

// dataTemplateNodeDao is the data access object for table data_template_node.
// You can define custom methods on it to extend its functionality as you wish.
type dataTemplateNodeDao struct {
	internalDataTemplateNodeDao
}

var (
	// DataTemplateNode is globally public accessible object for table data_template_node operations.
	DataTemplateNode = dataTemplateNodeDao{
		internal.NewDataTemplateNodeDao(),
	}
)

// Fill with you ideas below.
