// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/sagoo-cloud/sagooiot/internal/dao/internal"
)

// internalDataTemplateDao is internal type for wrapping internal DAO implements.
type internalDataTemplateDao = *internal.DataTemplateDao

// dataTemplateDao is the data access object for table data_template.
// You can define custom methods on it to extend its functionality as you wish.
type dataTemplateDao struct {
	internalDataTemplateDao
}

var (
	// DataTemplate is globally public accessible object for table data_template operations.
	DataTemplate = dataTemplateDao{
		internal.NewDataTemplateDao(),
	}
)

// Fill with you ideas below.
