// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/sagoo-cloud/sagooiot/internal/dao/internal"
)

// internalDataNodeDao is internal type for wrapping internal DAO implements.
type internalDataNodeDao = *internal.DataNodeDao

// dataNodeDao is the data access object for table data_node.
// You can define custom methods on it to extend its functionality as you wish.
type dataNodeDao struct {
	internalDataNodeDao
}

var (
	// DataNode is globally public accessible object for table data_node operations.
	DataNode = dataNodeDao{
		internal.NewDataNodeDao(),
	}
)

// Fill with you ideas below.
