// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sagooiot/internal/dao/internal"
)

// internalDevProductDao is internal type for wrapping internal DAO implements.
type internalDevProductDao = *internal.DevProductDao

// devProductDao is the data access object for table dev_product.
// You can define custom methods on it to extend its functionality as you wish.
type devProductDao struct {
	internalDevProductDao
}

var (
	// DevProduct is globally public accessible object for table dev_product operations.
	DevProduct = devProductDao{
		internal.NewDevProductDao(),
	}
)

// Fill with you ideas below.
