// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sagooiot/internal/dao/internal"
)

// internalDevDeviceTreeInfoDao is internal type for wrapping internal DAO implements.
type internalDevDeviceTreeInfoDao = *internal.DevDeviceTreeInfoDao

// devDeviceTreeInfoDao is the data access object for table dev_device_tree_info.
// You can define custom methods on it to extend its functionality as you wish.
type devDeviceTreeInfoDao struct {
	internalDevDeviceTreeInfoDao
}

var (
	// DevDeviceTreeInfo is globally public accessible object for table dev_device_tree_info operations.
	DevDeviceTreeInfo = devDeviceTreeInfoDao{
		internal.NewDevDeviceTreeInfoDao(),
	}
)

// Fill with you ideas below.
