// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sagooiot/internal/dao/internal"
)

// internalDevProductCategoryDao is internal type for wrapping internal DAO implements.
type internalDevProductCategoryDao = *internal.DevProductCategoryDao

// devProductCategoryDao is the data access object for table dev_product_category.
// You can define custom methods on it to extend its functionality as you wish.
type devProductCategoryDao struct {
	internalDevProductCategoryDao
}

var (
	// DevProductCategory is globally public accessible object for table dev_product_category operations.
	DevProductCategory = devProductCategoryDao{
		internal.NewDevProductCategoryDao(),
	}
)

// Fill with you ideas below.
