// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sagooiot/internal/dao/internal"
)

// internalDevDeviceGatewayDao is internal type for wrapping internal DAO implements.
type internalDevDeviceGatewayDao = *internal.DevDeviceGatewayDao

// devDeviceGatewayDao is the data access object for table dev_device_gateway.
// You can define custom methods on it to extend its functionality as you wish.
type devDeviceGatewayDao struct {
	internalDevDeviceGatewayDao
}

var (
	// DevDeviceGateway is globally public accessible object for table dev_device_gateway operations.
	DevDeviceGateway = devDeviceGatewayDao{
		internal.NewDevDeviceGatewayDao(),
	}
)

// Fill with you ideas below.
