// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sagooiot/internal/dao/internal"
)

// internalNoticeInfoDao is internal type for wrapping internal DAO implements.
type internalNoticeInfoDao = *internal.NoticeInfoDao

// noticeInfoDao is the data access object for table notice_info.
// You can define custom methods on it to extend its functionality as you wish.
type noticeInfoDao struct {
	internalNoticeInfoDao
}

var (
	// NoticeInfo is globally public accessible object for table notice_info operations.
	NoticeInfo = noticeInfoDao{
		internal.NewNoticeInfoDao(),
	}
)

// Fill with you ideas below.
