// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sagooiot/internal/dao/internal"
)

// internalNoticeLogDao is internal type for wrapping internal DAO implements.
type internalNoticeLogDao = *internal.NoticeLogDao

// noticeLogDao is the data access object for table notice_log.
// You can define custom methods on it to extend its functionality as you wish.
type noticeLogDao struct {
	internalNoticeLogDao
}

var (
	// NoticeLog is globally public accessible object for table notice_log operations.
	NoticeLog = noticeLogDao{
		internal.NewNoticeLogDao(),
	}
)

// Fill with you ideas below.
