// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sagooiot/internal/dao/internal"
)

// internalNoticeTemplateDao is internal type for wrapping internal DAO implements.
type internalNoticeTemplateDao = *internal.NoticeTemplateDao

// noticeTemplateDao is the data access object for table notice_template.
// You can define custom methods on it to extend its functionality as you wish.
type noticeTemplateDao struct {
	internalNoticeTemplateDao
}

var (
	// NoticeTemplate is globally public accessible object for table notice_template operations.
	NoticeTemplate = noticeTemplateDao{
		internal.NewNoticeTemplateDao(),
	}
)

// Fill with you ideas below.
