// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sagooiot/internal/dao/internal"
)

// internalOauthUserDao is internal type for wrapping internal DAO implements.
type internalOauthUserDao = *internal.OauthUserDao

// oauthUserDao is the data access object for table oauth_user.
// You can define custom methods on it to extend its functionality as you wish.
type oauthUserDao struct {
	internalOauthUserDao
}

var (
	// OauthUser is globally public accessible object for table oauth_user operations.
	OauthUser = oauthUserDao{
		internal.NewOauthUserDao(),
	}
)

// Fill with you ideas below.
