// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sagooiot/internal/dao/internal"
)

// internalOauthProviderDao is internal type for wrapping internal DAO implements.
type internalOauthProviderDao = *internal.OauthProviderDao

// oauthProviderDao is the data access object for table oauth_provider.
// You can define custom methods on it to extend its functionality as you wish.
type oauthProviderDao struct {
	internalOauthProviderDao
}

var (
	// OauthProvider is globally public accessible object for table oauth_provider operations.
	OauthProvider = oauthProviderDao{
		internal.NewOauthProviderDao(),
	}
)

// Fill with you ideas below.
