// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/sagoo-cloud/sagooiot/internal/dao/internal"
)

// internalRemoteconfDao is internal type for wrapping internal DAO implements.
type internalRemoteconfDao = *internal.RemoteconfDao

// remoteconfDao is the data access object for table remoteconf.
// You can define custom methods on it to extend its functionality as you wish.
type remoteconfDao struct {
	internalRemoteconfDao
}

var (
	// Remoteconf is globally public accessible object for table remoteconf operations.
	Remoteconf = remoteconfDao{
		internal.NewRemoteconfDao(),
	}
)

// Fill with you ideas below.
