// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sagooiot/internal/dao/internal"
)

// internalSysCertificateDao is internal type for wrapping internal DAO implements.
type internalSysCertificateDao = *internal.SysCertificateDao

// sysCertificateDao is the data access object for table sys_certificate.
// You can define custom methods on it to extend its functionality as you wish.
type sysCertificateDao struct {
	internalSysCertificateDao
}

var (
	// SysCertificate is globally public accessible object for table sys_certificate operations.
	SysCertificate = sysCertificateDao{
		internal.NewSysCertificateDao(),
	}
)

// Fill with you ideas below.
