// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sagooiot/internal/dao/internal"
)

// internalSysMessagereceiveDao is internal type for wrapping internal DAO implements.
type internalSysMessagereceiveDao = *internal.SysMessagereceiveDao

// sysMessagereceiveDao is the data access object for table sys_messagereceive.
// You can define custom methods on it to extend its functionality as you wish.
type sysMessagereceiveDao struct {
	internalSysMessagereceiveDao
}

var (
	// SysMessagereceive is globally public accessible object for table sys_messagereceive operations.
	SysMessagereceive = sysMessagereceiveDao{
		internal.NewSysMessagereceiveDao(),
	}
)

// Fill with you ideas below.
