// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sagooiot/internal/dao/internal"
)

// internalSysNotificationsDao is internal type for wrapping internal DAO implements.
type internalSysNotificationsDao = *internal.SysNotificationsDao

// sysNotificationsDao is the data access object for table sys_notifications.
// You can define custom methods on it to extend its functionality as you wish.
type sysNotificationsDao struct {
	internalSysNotificationsDao
}

var (
	// SysNotifications is globally public accessible object for table sys_notifications operations.
	SysNotifications = sysNotificationsDao{
		internal.NewSysNotificationsDao(),
	}
)

// Fill with you ideas below.
