// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sagooiot/internal/dao/internal"
)

// internalSysUserPasswordHistoryDao is internal type for wrapping internal DAO implements.
type internalSysUserPasswordHistoryDao = *internal.SysUserPasswordHistoryDao

// sysUserPasswordHistoryDao is the data access object for table sys_user_password_history.
// You can define custom methods on it to extend its functionality as you wish.
type sysUserPasswordHistoryDao struct {
	internalSysUserPasswordHistoryDao
}

var (
	// SysUserPasswordHistory is globally public accessible object for table sys_user_password_history operations.
	SysUserPasswordHistory = sysUserPasswordHistoryDao{
		internal.NewSysUserPasswordHistoryDao(),
	}
)

// Fill with you ideas below.
