// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sagooiot/internal/dao/internal"
)

// internalSysMenuButtonDao is internal type for wrapping internal DAO implements.
type internalSysMenuButtonDao = *internal.SysMenuButtonDao

// sysMenuButtonDao is the data access object for table sys_menu_button.
// You can define custom methods on it to extend its functionality as you wish.
type sysMenuButtonDao struct {
	internalSysMenuButtonDao
}

var (
	// SysMenuButton is globally public accessible object for table sys_menu_button operations.
	SysMenuButton = sysMenuButtonDao{
		internal.NewSysMenuButtonDao(),
	}
)

// Fill with you ideas below.
