// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sagooiot/internal/dao/internal"
)

// internalSysMenuApiDao is internal type for wrapping internal DAO implements.
type internalSysMenuApiDao = *internal.SysMenuApiDao

// sysMenuApiDao is the data access object for table sys_menu_api.
// You can define custom methods on it to extend its functionality as you wish.
type sysMenuApiDao struct {
	internalSysMenuApiDao
}

var (
	// SysMenuApi is globally public accessible object for table sys_menu_api operations.
	SysMenuApi = sysMenuApiDao{
		internal.NewSysMenuApiDao(),
	}
)

// Fill with you ideas below.
