// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sagooiot/internal/dao/internal"
)

// internalSysPluginsDao is internal type for wrapping internal DAO implements.
type internalSysPluginsDao = *internal.SysPluginsDao

// sysPluginsDao is the data access object for table sys_plugins.
// You can define custom methods on it to extend its functionality as you wish.
type sysPluginsDao struct {
	internalSysPluginsDao
}

var (
	// SysPlugins is globally public accessible object for table sys_plugins operations.
	SysPlugins = sysPluginsDao{
		internal.NewSysPluginsDao(),
	}
)

// Fill with you ideas below.
