// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sagooiot/internal/dao/internal"
)

// internalSysAuthorizeDao is internal type for wrapping internal DAO implements.
type internalSysAuthorizeDao = *internal.SysAuthorizeDao

// sysAuthorizeDao is the data access object for table sys_authorize.
// You can define custom methods on it to extend its functionality as you wish.
type sysAuthorizeDao struct {
	internalSysAuthorizeDao
}

var (
	// SysAuthorize is globally public accessible object for table sys_authorize operations.
	SysAuthorize = sysAuthorizeDao{
		internal.NewSysAuthorizeDao(),
	}
)

// Fill with you ideas below.
