// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sagooiot/internal/dao/internal"
)

// internalSysPluginsConfigDao is internal type for wrapping internal DAO implements.
type internalSysPluginsConfigDao = *internal.SysPluginsConfigDao

// sysPluginsConfigDao is the data access object for table sys_plugins_config.
// You can define custom methods on it to extend its functionality as you wish.
type sysPluginsConfigDao struct {
	internalSysPluginsConfigDao
}

var (
	// SysPluginsConfig is globally public accessible object for table sys_plugins_config operations.
	SysPluginsConfig = sysPluginsConfigDao{
		internal.NewSysPluginsConfigDao(),
	}
)

// Fill with you ideas below.
