// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sagooiot/internal/dao/internal"
)

// internalSysMessageDao is internal type for wrapping internal DAO implements.
type internalSysMessageDao = *internal.SysMessageDao

// sysMessageDao is the data access object for table sys_message.
// You can define custom methods on it to extend its functionality as you wish.
type sysMessageDao struct {
	internalSysMessageDao
}

var (
	// SysMessage is globally public accessible object for table sys_message operations.
	SysMessage = sysMessageDao{
		internal.NewSysMessageDao(),
	}
)

// Fill with you ideas below.
