// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// AlarmRule is the golang structure for table alarm_rule.
type AlarmRule struct {
	Id               uint64      `json:"id"               description:""`
	Name             string      `json:"name"             description:"告警规则名称"`
	Level            uint        `json:"level"            description:"告警级别，默认：4（一般）"`
	ProductKey       string      `json:"productKey"       description:"产品标识"`
	DeviceKey        string      `json:"deviceKey"        description:"设备标识"`
	TriggerType      int         `json:"triggerType"      description:"触发类型：1=上线，2=离线，3=属性上报"`
	TriggerCondition string      `json:"triggerCondition" description:"触发条件"`
	Action           string      `json:"action"           description:"执行动作"`
	Status           int         `json:"status"           description:"状态：0=未启用，1=已启用"`
	CreateBy         uint        `json:"createBy"         description:"创建者"`
	UpdateBy         uint        `json:"updateBy"         description:"更新者"`
	DeletedBy        uint        `json:"deletedBy"        description:"删除者"`
	CreatedAt        *gtime.Time `json:"createdAt"        description:"创建时间"`
	UpdatedAt        *gtime.Time `json:"updatedAt"        description:"更新时间"`
	DeletedAt        *gtime.Time `json:"deletedAt"        description:"删除时间"`
}
