// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// CityData is the golang structure for table city_data.
type CityData struct {
	Id        int         `json:"id"        description:""`
	Name      string      `json:"name"      description:"名字"`
	Code      string      `json:"code"      description:"编码"`
	ParentId  int         `json:"parentId"  description:"父ID"`
	Sort      int         `json:"sort"      description:"排序"`
	Status    uint        `json:"status"    description:"状态;0:禁用;1:正常"`
	IsDeleted int         `json:"isDeleted" description:"是否删除 0未删除 1已删除"`
	CreatedBy uint        `json:"createdBy" description:"创建者"`
	CreatedAt *gtime.Time `json:"createdAt" description:"创建日期"`
	UpdatedBy uint        `json:"updatedBy" description:"更新者"`
	UpdatedAt *gtime.Time `json:"updatedAt" description:"修改日期"`
	DeletedBy int         `json:"deletedBy" description:"删除人"`
	DeletedAt *gtime.Time `json:"deletedAt" description:"删除时间"`
}
