// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// DataSource is the golang structure for table data_source.
type DataSource struct {
	SourceId  uint64      `json:"sourceId"  description:""`
	Name      string      `json:"name"      description:"数据源名称"`
	Key       string      `json:"key"       description:"数据源标识"`
	Desc      string      `json:"desc"      description:"描述"`
	From      int         `json:"from"      description:"数据来源：1=api导入，2=数据库，3=文件，4=设备"`
	Config    string      `json:"config"    description:"数据源配置json：api配置、数据库配置、文件配置"`
	Rule      string      `json:"rule"      description:"规则配置json"`
	LockKey   int         `json:"lockKey"   description:"锁定key标识：0=未锁定，1=锁定，不允许修改"`
	Status    int         `json:"status"    description:"状态：0=未发布，1=已发布"`
	DataTable string      `json:"dataTable" description:"数据表名称"`
	CreateBy  uint        `json:"createBy"  description:"创建者"`
	UpdateBy  uint        `json:"updateBy"  description:"更新者"`
	DeletedBy uint        `json:"deletedBy" description:"删除者"`
	CreatedAt *gtime.Time `json:"createdAt" description:"创建时间"`
	UpdatedAt *gtime.Time `json:"updatedAt" description:"更新时间"`
	DeletedAt *gtime.Time `json:"deletedAt" description:"删除时间"`
}
