// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// DataTemplateNode is the golang structure for table data_template_node.
type DataTemplateNode struct {
	Id        uint64      `json:"id"        description:"ID"`
	Tid       uint64      `json:"tid"       description:"模型ID"`
	From      int         `json:"from"      description:"字段生成方式:1=自动生成,2=数据源"`
	SourceId  uint64      `json:"sourceId"  description:"数据源ID"`
	NodeId    uint64      `json:"nodeId"    description:"数据源ID"`
	Name      string      `json:"name"      description:"节点名称"`
	Key       string      `json:"key"       description:"节点标识"`
	DataType  string      `json:"dataType"  description:"数据类型"`
	Default   string      `json:"default"   description:"默认值"`
	Method    string      `json:"method"    description:"数值类型，取值方式"`
	IsPk      int         `json:"isPk"      description:"是否主键：0=否，1=是"`
	Desc      string      `json:"desc"      description:"描述"`
	CreateBy  uint        `json:"createBy"  description:"创建者"`
	UpdateBy  uint        `json:"updateBy"  description:"更新者"`
	DeletedBy uint        `json:"deletedBy" description:"删除者"`
	CreatedAt *gtime.Time `json:"createdAt" description:"创建时间"`
	UpdatedAt *gtime.Time `json:"updatedAt" description:"更新时间"`
	DeletedAt *gtime.Time `json:"deletedAt" description:"删除时间"`
}
