// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// DataNode is the golang structure for table data_node.
type DataNode struct {
	NodeId    uint64      `json:"nodeId"    description:""`
	SourceId  uint64      `json:"sourceId"  description:"数据源ID"`
	Name      string      `json:"name"      description:"数据节点名称"`
	Key       string      `json:"key"       description:"数据节点标识"`
	DataType  string      `json:"dataType"  description:"数据类型"`
	Value     string      `json:"value"     description:"取值项"`
	IsPk      int         `json:"isPk"      description:"是否主键：0=否，1=是"`
	Rule      string      `json:"rule"      description:"规则配置json"`
	CreateBy  uint        `json:"createBy"  description:"创建者"`
	UpdateBy  uint        `json:"updateBy"  description:"更新者"`
	DeletedBy uint        `json:"deletedBy" description:"删除者"`
	CreatedAt *gtime.Time `json:"createdAt" description:"创建时间"`
	UpdatedAt *gtime.Time `json:"updatedAt" description:"更新时间"`
	DeletedAt *gtime.Time `json:"deletedAt" description:"删除时间"`
}
