// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// DataTemplateBusi is the golang structure for table data_template_busi.
type DataTemplateBusi struct {
	Id             int         `json:"id"             description:""`
	DataTemplateId int         `json:"dataTemplateId" description:"数据建模ID"`
	BusiTypes      int         `json:"busiTypes"      description:"业务单元"`
	IsDeleted      int         `json:"isDeleted"      description:"0未删除 1已删除"`
	CreatedBy      uint        `json:"createdBy"      description:"创建人"`
	CreatedAt      *gtime.Time `json:"createdAt"      description:"创建时间"`
	DeletedBy      int         `json:"deletedBy"      description:"删除人"`
	DeletedAt      *gtime.Time `json:"deletedAt"      description:"删除时间"`
}
