// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// DataTemplate is the golang structure for table data_template.
type DataTemplate struct {
	Id             uint64      `json:"id"             description:"ID"`
	Name           string      `json:"name"           description:"名称"`
	Key            string      `json:"key"            description:"标识"`
	Desc           string      `json:"desc"           description:"描述"`
	Status         int         `json:"status"         description:"状态：0=未发布，1=已发布"`
	CronExpression string      `json:"cronExpression" description:"cron执行表达式"`
	SortNodeKey    string      `json:"sortNodeKey"    description:"排序节点标识"`
	SortDesc       int         `json:"sortDesc"       description:"排序方式：1=倒序，2=正序"`
	DataTable      string      `json:"dataTable"      description:"数据表名称"`
	LockKey        int         `json:"lockKey"        description:"锁定key标识：0=未锁定，1=锁定，不允许修改"`
	MainSourceId   uint64      `json:"mainSourceId"   description:"主数据源"`
	SourceNodeKey  string      `json:"sourceNodeKey"  description:"数据源关联节点"`
	CreateBy       uint        `json:"createBy"       description:"创建者"`
	UpdateBy       uint        `json:"updateBy"       description:"更新者"`
	DeletedBy      uint        `json:"deletedBy"      description:"删除者"`
	CreatedAt      *gtime.Time `json:"createdAt"      description:"创建时间"`
	UpdatedAt      *gtime.Time `json:"updatedAt"      description:"更新时间"`
	DeletedAt      *gtime.Time `json:"deletedAt"      description:"删除时间"`
}
