// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// DevDevice is the golang structure for table dev_device.
type DevDevice struct {
	Id             uint        `json:"id"             description:""`
	Key            string      `json:"key"            description:"设备标识"`
	Name           string      `json:"name"           description:"设备名称"`
	ProductId      uint        `json:"productId"      description:"所属产品"`
	Desc           string      `json:"desc"           description:"描述"`
	MetadataTable  int         `json:"metadataTable"  description:"是否生成物模型子表：0=否，1=是"`
	Status         int         `json:"status"         description:"状态：0=未启用,1=离线,2=在线"`
	RegistryTime   *gtime.Time `json:"registryTime"   description:"激活时间"`
	LastOnlineTime *gtime.Time `json:"lastOnlineTime" description:"最后上线时间"`
	Certificate    string      `json:"certificate"    description:"设备证书"`
	SecureKey      string      `json:"secureKey"      description:"设备密钥"`
	Version        string      `json:"version"        description:"固件版本号"`
	TunnelId       int         `json:"tunnelId"       description:"tunnelId"`
	CreateBy       uint        `json:"createBy"       description:"创建者"`
	UpdateBy       uint        `json:"updateBy"       description:"更新者"`
	DeletedBy      uint        `json:"deletedBy"      description:"删除者"`
	CreatedAt      *gtime.Time `json:"createdAt"      description:"创建时间"`
	UpdatedAt      *gtime.Time `json:"updatedAt"      description:"更新时间"`
	DeletedAt      *gtime.Time `json:"deletedAt"      description:"删除时间"`
}
