// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// DevProductCategory is the golang structure for table dev_product_category.
type DevProductCategory struct {
	Id        uint        `json:"id"        description:""`
	ParentId  uint        `json:"parentId"  description:"父ID"`
	Key       string      `json:"key"       description:"分类标识"`
	Name      string      `json:"name"      description:"分类名称"`
	Desc      string      `json:"desc"      description:"描述"`
	CreateBy  uint        `json:"createBy"  description:"创建者"`
	UpdateBy  uint        `json:"updateBy"  description:"更新者"`
	DeletedBy uint        `json:"deletedBy" description:"删除者"`
	CreatedAt *gtime.Time `json:"createdAt" description:"创建时间"`
	UpdatedAt *gtime.Time `json:"updatedAt" description:"更新时间"`
	DeletedAt *gtime.Time `json:"deletedAt" description:"删除时间"`
}
